sudo: required
services:
  - docker

before_install:
  - docker build -t esgras/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true esgras/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-673912013739"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  # Plain text, no need secure key
  secret_access_key: $AWS_SECRET_KEY