name: Deploy to GitHub Pages
on:
 push:
   branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t esgras/k8sphp -f Dockerfile.dev .
      - name: Run tests
        run: docker run --env CI=true esgras/k8sphp npm run test -- --coverage